/**
 * Regenerates app/game/data/generated/*.ts from the AsyncTI4 data set
 * (https://github.com/AsyncTI4/TI4_map_generator_bot, Unlicense).
 *
 * Only official content is kept (base, Prophecy of Kings, Codex I-IV,
 * Thunder's Edge); art URLs and flavor text are dropped.
 *
 *   npx tsx scripts/importGameData.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { rawSystems } from "../app/data/rawSystemData";
import type { FactionId, TechSpecialty } from "../app/types";
import type {
  AbilityData,
  ActionCardData,
  AgendaData,
  AgendaTarget,
  AttachmentData,
  BreakthroughData,
  ContentSource,
  ExplorationData,
  FactionSetupData,
  GalacticEventData,
  LeaderData,
  ObjectiveData,
  PromissoryNoteData,
  RelicData,
  StartingUnits,
  StrategyCardData,
  TechnologyData,
  UnitData,
  UnitType,
} from "../app/game/data/types";

const COMMIT = "9e51354b7fed24702873ca62d93b81067d4334a7";
const BASE_URL = `https://raw.githubusercontent.com/AsyncTI4/TI4_map_generator_bot/${COMMIT}/src/main/resources/data`;
const OUT_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "../app/game/data/generated",
);

const SOURCES: Record<string, ContentSource> = {
  base: "base",
  pok: "pok",
  codex1: "codex1",
  codex2: "codex2",
  codex3: "codex3",
  codex4: "codex4",
  thunders_edge: "te",
};

const FACTION_ALIASES: Record<string, FactionId> = {
  letnev: "barony",
  ghost: "creuss",
  cabal: "vulraith",
  naaz: "naazrokha",
  deepwrought: "dws",
  // The Obsidian is the Firmament's flipped side.
  obsidian: "firmament",
  keleresm: "keleres",
  keleresx: "keleres",
  keleresa: "keleres",
};

const KELERES_VARIANTS: Record<string, FactionId> = {
  keleresm: "mentak",
  keleresx: "xxcha",
  keleresa: "argent",
};

const UNIT_TYPES: Record<string, UnitType> = {
  carrier: "carrier",
  cruiser: "cruiser",
  destroyer: "destroyer",
  dreadnought: "dreadnought",
  fighter: "fighter",
  flagship: "flagship",
  infantry: "infantry",
  mech: "mech",
  pds: "pds",
  spacedock: "spacedock",
  warsun: "warsun",
};

const FLEET_CODES: Record<string, UnitType> = {
  cv: "carrier",
  cr: "cruiser",
  ca: "cruiser",
  dd: "destroyer",
  dn: "dreadnought",
  ff: "fighter",
  fs: "flagship",
  ws: "warsun",
  inf: "infantry",
  mech: "mech",
  pds: "pds",
  sd: "spacedock",
};

const TECH_COLORS: Record<string, TechSpecialty> = {
  B: "PROPULSION",
  G: "BIOTIC",
  R: "WARFARE",
  Y: "CYBERNETIC",
  PROPULSION: "PROPULSION",
  BIOTIC: "BIOTIC",
  WARFARE: "WARFARE",
  CYBERNETIC: "CYBERNETIC",
};

// The source files are loosely shaped JSON.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Raw = Record<string, any>;

async function load(path: string): Promise<Raw[]> {
  const response = await fetch(`${BASE_URL}/${path}`);
  if (!response.ok) throw new Error(`${path}: ${response.status}`);
  const data = (await response.json()) as Raw[];
  return data.filter((item) => item.source in SOURCES);
}

const loadAll = async (...paths: string[]) =>
  (await Promise.all(paths.map(load))).flat();

const source = (raw: Raw) => SOURCES[raw.source];
const faction = (id: string): FactionId =>
  FACTION_ALIASES[id] ?? (id as FactionId);
const clean = (text?: string) => (text ?? "").trim();
const normalize = (name: string) => name.toLowerCase().replace(/[^a-z0-9]/g, "");

function write(file: string, type: string, name: string, data: unknown) {
  const body = [
    "// Generated by scripts/importGameData.ts. Do not edit by hand.",
    `import type { ${type} } from "../types";`,
    "",
    `export const ${name}: ${type}[] = ${JSON.stringify(data, null, 2)};`,
    "",
  ].join("\n");
  writeFileSync(join(OUT_DIR, file), body);
  console.log(`${file}: ${(data as unknown[]).length}`);
}

function toUnit(raw: Raw): UnitData | undefined {
  const type = UNIT_TYPES[raw.baseType];
  if (!type || raw.id === "nowarsun") return undefined;
  const plusResources =
    typeof raw.productionValue === "string" &&
    raw.productionValue.startsWith("+");
  return {
    id: raw.id,
    type,
    name: raw.name,
    source: source(raw),
    faction: raw.faction ? faction(raw.faction) : undefined,
    requiredTechId: raw.requiredTechId,
    upgradesFromUnitId: raw.upgradesFromUnitId,
    upgradesToUnitId: raw.upgradesToUnitId,
    cost: raw.cost === undefined ? undefined : Math.ceil(raw.cost),
    producedPerCost: raw.cost === 0.5 ? 2 : 1,
    move: raw.moveValue,
    capacity: raw.capacityValue,
    combat: raw.combatHitsOn,
    combatDice: raw.combatDieCount,
    afb: raw.afbHitsOn,
    afbDice: raw.afbDieCount,
    bombardment: raw.bombardHitsOn,
    bombardmentDice: raw.bombardDieCount,
    spaceCannon: raw.spaceCannonHitsOn,
    spaceCannonDice: raw.spaceCannonDieCount,
    deepSpaceCannon: raw.deepSpaceCannon,
    sustainDamage: raw.sustainDamage,
    planetaryShield: raw.planetaryShield,
    disablesPlanetaryShield: raw.disablesPlanetaryShield,
    production: plusResources
      ? undefined
      : raw.productionValue === undefined
        ? undefined
        : Number(raw.productionValue),
    productionPlusResources: plusResources
      ? Number(raw.productionValue)
      : undefined,
    spaceOnly: raw.isSpaceOnly,
    ability: raw.ability,
  };
}

function toTechnology(raw: Raw): TechnologyData {
  const types: string[] = raw.types ?? [];
  return {
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    color: types.map((t) => TECH_COLORS[t]).find(Boolean),
    unitUpgrade: types.includes("UNITUPGRADE"),
    prerequisites: [...(raw.requirements ?? "")]
      .map((c: string) => TECH_COLORS[c])
      .filter(Boolean),
    faction: raw.faction ? faction(raw.faction) : undefined,
    baseUpgrade: raw.baseUpgrade,
    text: clean(raw.text),
  };
}

function agendaTarget(target: string): AgendaTarget {
  const t = target.toLowerCase();
  if (t === "for/against") return "forAgainst";
  if (t === "elect player") return "player";
  if (t.startsWith("elect non-home planet")) return "nonHomePlanet";
  if (t === "elect cultural planet") return "culturalPlanet";
  if (t === "elect hazardous planet") return "hazardousPlanet";
  if (t === "elect industrial planet") return "industrialPlanet";
  if (t === "elect planet") return "planet";
  if (t.startsWith("elect scored secret")) return "scoredSecret";
  if (t.startsWith("elect law")) return "law";
  if (t === "elect strategy card") return "strategyCard";
  return "other";
}

/** Home planet names as this repo spells them, keyed by faction. */
function homePlanetNames(id: FactionId): string[] {
  const system = Object.values(rawSystems).find(
    (s) => s.faction === id && s.type === "GREEN",
  );
  return system?.planets.map((p) => p.name) ?? [];
}

function resolvePlanet(
  hint: string,
  planets: string[],
  sourceIds: string[],
  owner: string,
) {
  if (planets.length === 0) throw new Error(`${owner}: no home planets`);
  if (!hint) return planets[0];
  const wanted = normalize(hint);
  const initials = (name: string) =>
    name
      .split(/[^A-Za-z0-9]+/)
      .filter(Boolean)
      .map((w) => w[0].toLowerCase())
      .join("");
  const matches =
    [
      planets.filter((p) => normalize(p) === wanted),
      planets.filter((p) => initials(p) === wanted),
      planets.filter((p) => normalize(p).startsWith(wanted)),
      // The data set spells some planets differently; its home planets are
      // listed in the same order as ours, so fall back to position.
      sourceIds.length === planets.length
        ? planets.filter((_, idx) => normalize(sourceIds[idx]).startsWith(wanted))
        : [],
    ].find((m) => m.length === 1) ?? [];
  if (matches.length !== 1) {
    throw new Error(`${owner}: cannot place "${hint}" on ${planets}`);
  }
  return matches[0];
}

function toStartingUnits(
  fleet: string,
  planets: string[],
  sourceIds: string[],
  owner: string,
): StartingUnits {
  const units: StartingUnits = { space: {}, planets: {} };
  fleet
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .forEach((part) => {
      const match = part.match(/^(\d+)?\s*([a-z]+)\s*(.*)$/i);
      if (!match) throw new Error(`${owner}: cannot parse "${part}"`);
      const [, count, code, hint] = match;
      const type = FLEET_CODES[code.toLowerCase()];
      if (!type) throw new Error(`${owner}: unknown unit "${code}"`);
      const amount = Number(count ?? 1);
      const inSpace =
        !["infantry", "mech", "pds", "spacedock"].includes(type) ||
        // Floating Factory starts in the space area.
        (type === "spacedock" && owner === "saar");
      if (inSpace) {
        units.space[type] = (units.space[type] ?? 0) + amount;
        return;
      }
      const planet = resolvePlanet(hint.trim(), planets, sourceIds, owner);
      units.planets[planet] ??= {};
      units.planets[planet][type] = (units.planets[planet][type] ?? 0) + amount;
    });
  return units;
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const units = (
    await loadAll(
      "units/baseUnits.json",
      "units/pok.json",
      "units/keleres.json",
      "units/te_units.json",
    )
  )
    .map(toUnit)
    .filter((u): u is UnitData => u !== undefined);
  write("units.ts", "UnitData", "units", units);

  const technologies = (
    await loadAll("technologies/pok.json", "technologies/te_techs.json")
  ).map(toTechnology);
  write("technologies.ts", "TechnologyData", "technologies", technologies);

  const actionCards: ActionCardData[] = (
    await loadAll(
      "action_cards/action_cards.json",
      "action_cards/te_actioncards.json",
    )
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    phase: raw.phase,
    window: clean(raw.window),
    text: clean(raw.text),
    componentAction: clean(raw.window).toLowerCase() === "action",
  }));
  write("actionCards.ts", "ActionCardData", "actionCards", actionCards);

  const agendas: AgendaData[] = (
    await loadAll("agendas/base.json", "agendas/pok.json")
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    type: raw.type === "Law" ? "law" : "directive",
    target: agendaTarget(raw.target),
    targetText: clean(raw.target),
    text1: clean(raw.text1),
    text2: clean(raw.text2),
  }));
  write("agendas.ts", "AgendaData", "agendas", agendas);

  const publics: ObjectiveData[] = (
    await load("public_objectives/public_objectives.json")
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    kind: raw.points === 1 ? "stage1" : "stage2",
    phase: raw.phase.toLowerCase(),
    points: raw.points,
    text: clean(raw.text),
  }));
  const secrets: ObjectiveData[] = (
    await load("secret_objectives/secret_objectives.json")
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    kind: "secret",
    phase: raw.phase.toLowerCase(),
    points: raw.points,
    text: clean(raw.text),
  }));
  write("objectives.ts", "ObjectiveData", "objectives", [
    ...publics,
    ...secrets,
  ]);

  const strategyCards: StrategyCardData[] = (
    await loadAll("strategy_cards/pok.json", "strategy_cards/te.json")
  ).map((raw) => ({
    id: raw.id,
    name: raw.name,
    source: source(raw),
    initiative: raw.initiative,
    color: raw.colourHexCode,
    primary: raw.primaryTexts,
    secondary: raw.secondaryTexts,
  }));
  write(
    "strategyCards.ts",
    "StrategyCardData",
    "strategyCards",
    strategyCards,
  );

  const explorations: ExplorationData[] = (
    await loadAll("explores/explores.json", "explores/codex3.json")
  ).map((raw) => ({
    id: raw.id,
    name: raw.name,
    source: source(raw),
    deck: raw.type.toLowerCase(),
    resolution: raw.resolution.toLowerCase(),
    attachmentId: raw.attachmentId,
    text: clean(raw.text),
  }));
  write(
    "explorations.ts",
    "ExplorationData",
    "explorations",
    explorations,
  );

  const attachments: AttachmentData[] = (
    await loadAll("attachments/attachments.json", "attachments/thundersEdge.json")
  )
    .filter((raw) => !raw.isFakeAttachment)
    .map((raw) => ({
      id: raw.id,
      name: raw.name,
      source: source(raw),
      resources: raw.resourcesModifier ?? 0,
      influence: raw.influenceModifier ?? 0,
      techSpecialty: (raw.techSpeciality ?? []).map(
        (t: string) => TECH_COLORS[t.toUpperCase()],
      ),
      legendary: raw.isLegendary,
    }));
  write("attachments.ts", "AttachmentData", "attachments", attachments);

  const relics: RelicData[] = (
    await loadAll(
      "relics/pok.json",
      "relics/codexii.json",
      "relics/codexiv.json",
      "relics/te_relics.json",
    )
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    text: clean(raw.text),
  }));
  write("relics.ts", "RelicData", "relics", relics);

  const leaders: LeaderData[] = (
    await loadAll("leaders/pok.json", "leaders/te_leaders.json")
  ).map((raw) => ({
    id: raw.id,
    faction: faction(raw.faction),
    source: source(raw),
    type: raw.type,
    name: raw.name,
    title: clean(raw.title),
    window: clean(raw.abilityWindow),
    text: clean(raw.abilityText),
    unlock: clean(raw.unlockCondition),
  }));
  write("leaders.ts", "LeaderData", "leaders", leaders);

  const promissoryNotes: PromissoryNoteData[] = (
    await loadAll(
      "promissory_notes/color.json",
      "promissory_notes/promissory_notes.json",
      "promissory_notes/thunders_edge.json",
    )
  ).map((raw) => ({
    id: raw.alias.replace("<color>_", ""),
    name: raw.name,
    source: source(raw),
    faction: raw.faction ? faction(raw.faction) : undefined,
    playArea: !!raw.playArea,
    text: clean(raw.text),
  }));
  write(
    "promissoryNotes.ts",
    "PromissoryNoteData",
    "promissoryNotes",
    promissoryNotes,
  );

  const abilities: AbilityData[] = (
    await loadAll(
      "abilities/base.json",
      "abilities/pok.json",
      "abilities/other.json",
      "abilities/te_abilities.json",
    )
  ).map((raw) => ({
    id: raw.id,
    name: raw.name,
    source: source(raw),
    faction: faction(raw.faction),
    text: [
      raw.permanentEffect,
      raw.window && raw.windowEffect
        ? `${raw.window}: ${raw.windowEffect}`
        : raw.windowEffect,
    ]
      .filter(Boolean)
      .map(clean)
      .join("\n"),
  }));
  write("abilities.ts", "AbilityData", "abilities", abilities);

  const breakthroughs: BreakthroughData[] = (
    await load("breakthroughs/te_breakthroughs.json")
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    faction: faction(raw.faction),
    synergy: (raw.synergy ?? [])
      .map((t: string) => TECH_COLORS[t])
      .filter(Boolean),
    text: clean(raw.text),
  }));
  write(
    "breakthroughs.ts",
    "BreakthroughData",
    "breakthroughs",
    breakthroughs,
  );

  const galacticEvents: GalacticEventData[] = (
    await load("galactic_events/te_galactic_events.json")
  ).map((raw) => ({
    id: raw.alias,
    name: raw.name,
    source: source(raw),
    text: clean(raw.text),
  }));
  write(
    "galacticEvents.ts",
    "GalacticEventData",
    "galacticEvents",
    galacticEvents,
  );

  const factionSetups: FactionSetupData[] = (
    await loadAll(
      "factions/base.json",
      "factions/pok.json",
      "factions/keleres.json",
      "factions/te_factions.json",
    )
  )
    // The Obsidian is the flipped side of the Firmament, not a starting faction.
    .filter((raw) => raw.alias !== "obsidian")
    .map((raw) => {
      const id = faction(raw.alias);
      const variant = KELERES_VARIANTS[raw.alias];
      const planets = homePlanetNames(variant ?? id);
      return {
        faction: id,
        variant,
        source: source(raw),
        commodities: raw.commodities,
        startingTech: raw.startingTech ?? [],
        startingTechOptions: raw.startingTechOptions ?? [],
        startingTechChoices: raw.startingTechAmount ?? 0,
        factionTech: raw.factionTech ?? [],
        abilities: raw.abilities ?? [],
        leaders: raw.leaders ?? [],
        promissoryNotes: raw.promissoryNotes ?? [],
        units: raw.units ?? [],
        breakthrough: breakthroughs.find((b) => b.faction === id)?.id,
        homePlanets: planets,
        startingUnits: toStartingUnits(
          // Keleres hints name planets from the Keleres-specific tiles.
          variant ? raw.startingFleet.replace(/\b\w+k$/, "") : raw.startingFleet,
          planets,
          raw.homePlanets ?? [],
          raw.alias,
        ),
      };
    });
  write(
    "factionSetups.ts",
    "FactionSetupData",
    "factionSetups",
    factionSetups,
  );

  // Every id a faction references must exist in the generated data.
  const known = {
    tech: new Set(technologies.map((t) => t.id)),
    unit: new Set(units.map((u) => u.id)),
    leader: new Set(leaders.map((l) => l.id)),
    ability: new Set(abilities.map((a) => a.id)),
    note: new Set(promissoryNotes.map((p) => p.id)),
  };
  for (const setup of factionSetups) {
    const missing = [
      ...[
        ...setup.startingTech,
        ...setup.startingTechOptions,
        ...setup.factionTech,
      ].filter((id) => !known.tech.has(id)),
      ...setup.units.filter((id) => !known.unit.has(id)),
      ...setup.leaders.filter((id) => !known.leader.has(id)),
      ...setup.abilities.filter((id) => !known.ability.has(id)),
      ...setup.promissoryNotes.filter((id) => !known.note.has(id)),
    ];
    if (missing.length > 0) {
      console.warn(`${setup.faction}: unresolved ids ${missing.join(", ")}`);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
